# Generated by Django 4.0.1 on 2022-02-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place_name', models.CharField(max_length=30)),
                ('place_details', models.TextField()),
                ('image', models.ImageField(upload_to='name/place')),
            ],
        ),
    ]
