# Generated by Django 4.0.1 on 2022-02-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_details',
            new_name='details',
        ),
    ]
